#!/bin/bash

for ((i=0; i<8; i++)); do
  for ((j=0; j<8; j++)); do
    for ((k=0; k<8; k++)); do
	   string_to_eval="\$'abc\\${i}${j}${k}def'"
	   command_to_eval='test='$string_to_eval
	   echo using $command_to_eval to test the value of $string_to_eval
	   # eval string_to_eval
	   # print the value of $test
	   # $test should in theory be 7 characters long after the eval.  is it?  check its length explicitly
    done
  done
done

exit 0