#!/bin/bash

# script requires exactly 1 parameter.  parameter must be a positive number.
#
if [ $# -ne 1 ]; then 
  echo '??' $0: exactly 1 argument required: "$#" supplied
  exit 2
fi
if ! grep -P "^\d*[1-9]\d*$" <<<$1 &>/dev/null ; then 
  echo '??' $0:  argument "($1)" must be a positive number
  exit 1
fi

# script's main body starts here
#
echo $0: counting from 0 to $1
for ((i=0; i<$1; i++)); do
  echo -n $i' '
done
echo

# end of script
#
exit 0